version: "3.9"  # можешь удалить по предупреждению

services:
  backend:
    build:
      context: ./backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      mynet:
        aliases:
          - server

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    networks:
      - mynet

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: webapp
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - mynet
networks:
  mynet:
    driver: bridge

volumes:
  db-data:
